### ISSUE TITLE
Please copy these files into a new repo

### ISSUE THREAD

**Issue by teddyxlandlee** [Over-Run/maven#1]
![IPKQ9CP JV%PXRSKKT8EDZM](https://user-images.githubusercontent.com/67260053/152672630-4627b5ac-adf3-4a4f-9b74-358715a7935b.png)

e.g.  
- Create new file `Over-Run/static` along with github-pages action
- Copy necessary JS & CSS files there
- Use them

**Comment by squid233** [comment]
done
